### ISSUE TITLE
Item Sub-Categories

### ISSUE THREAD

**Issue by MadCaper** [pbbg-io/titan-framework#15]
Parent and child categories for items, this would allow for another layer into the item system out of the box. IE: Weapons could have the sub categories; Swords, Knives, Guns, Axes etc

**Comment by 1e4** [comment]
Would you also want this to support schemas for items? So instead of
needing to click add stat on every item it can inherit it from a template
set in the item category?

Might save some time if your adding 5 axes and they all have strength,
attack, speed, endurence etc or however you want to setup your items

**Comment by 1e4** [comment]
I've added the ability for item categories to have parents
